version: '3.4'

services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5000:8080"
    volumes:
      - ./RRS.Api/uploads:/app/uploads

  client: 
    ports:
      - "5001:3000"

  proxy:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./RRS.Api/uploads:/usr/share/nginx/html/uploads
    ports:
      - "80:80"
